"""Add seeder 2

Revision ID: 769a05fc37c7
Revises: dd8f258c30ec
Create Date: 2023-02-10 22:29:09.196344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '769a05fc37c7'
down_revision = 'dd8f258c30ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.orm import Session
    from sqlalchemy import create_engine
    from app.models.account import Account
    from app.models.person import Person
    from app.models.account_type import AccountType
    
    engine = create_engine('mysql+pymysql://gabriel:143867@0.0.0.0:3306/mysql')

    name = "Gabriel"
    cpf = "59470129321" # Não real
    birth_date = "2001-06-19T00:00:00"

    email = 'siron@quickup.io'
    password = 'password'


    person_json = {
        'name': name,
        'cpf': cpf,
        'birth_date': birth_date
    }

    account_json = {
        'email': email,
        'password': password,
        'is_active': True
    }
    
    account_type_json = {
        'name': 'Conta Fácil',
        'drawing_limit': 1000.00
    }

    new_account = Account(**account_json)
    new_account.person = Person(**person_json)
    new_account.account_type = AccountType(**account_type_json)

    with Session(engine) as session:
        session.add_all([new_account])
        session.commit()



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
