"""Add seeder

Revision ID: dd8f258c30ec
Revises: 40f0cdf650ae
Create Date: 2023-02-10 22:05:09.523329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd8f258c30ec'
down_revision = '40f0cdf650ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.orm import Session
    from sqlalchemy import create_engine
    from app.models.account import Account
    from app.models.person import Person
    from app.models.account_type import AccountType
    
    engine = create_engine('mysql+pymysql://gabriel:143867@0.0.0.0:3306/mysql')

    name = "Gabriel"
    cpf = "59470129321" # Não real
    birth_date = "2001-06-19T00:00:00"

    email = 'siron@quickup.io'
    password = 'password'


    person_json = {
        'name': name,
        'cpf': cpf,
        'birth_date': birth_date
    }

    account_json = {
        'email': email,
        'password': password,
    }
    
    account_type_json = {
        'name': 'Conta Fácil',
        'drawing_limit': 1000.00
    }

    new_account = Account(**account_json)
    new_account.person = Person(**person_json)
    new_account.account_type = AccountType(**account_type_json)

    with Session(engine) as session:
        session.add_all([new_account])
        session.commit()

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('func',
    sa.Column('name', mysql.CHAR(collation='utf8mb3_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('ret', mysql.TINYINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('dl', mysql.CHAR(collation='utf8mb3_bin', length=128), server_default=sa.text("''"), nullable=False),
    sa.Column('type', mysql.ENUM('function', 'aggregate'), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    comment='User defined functions',
    mysql_collate='utf8mb3_bin',
    mysql_comment='User defined functions',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('component',
    sa.Column('component_id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('component_group_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('component_urn', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('component_id'),
    comment='Components',
    mysql_comment='Components',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('person',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('cpf', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('birth_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.create_index('cpf', ['cpf'], unique=False)

    op.create_table('innodb_table_stats',
    sa.Column('database_name', mysql.VARCHAR(collation='utf8mb3_bin', length=64), nullable=False),
    sa.Column('table_name', mysql.VARCHAR(collation='utf8mb3_bin', length=199), nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('n_rows', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('clustered_index_size', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('sum_of_other_index_sizes', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('database_name', 'table_name'),
    mysql_collate='utf8mb3_bin',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('role_edges',
    sa.Column('FROM_HOST', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('FROM_USER', mysql.CHAR(collation='utf8mb3_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('TO_HOST', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('TO_USER', mysql.CHAR(collation='utf8mb3_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('WITH_ADMIN_OPTION', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.PrimaryKeyConstraint('FROM_HOST', 'FROM_USER', 'TO_HOST', 'TO_USER'),
    comment='Role hierarchy and role grants',
    mysql_collate='utf8mb3_bin',
    mysql_comment='Role hierarchy and role grants',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('time_zone',
    sa.Column('Time_zone_id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('Use_leap_seconds', mysql.ENUM('Y', 'N'), server_default=sa.text("'N'"), nullable=False),
    sa.PrimaryKeyConstraint('Time_zone_id'),
    comment='Time zones',
    mysql_comment='Time zones',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('user',
    sa.Column('Host', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8mb3_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('Select_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Insert_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Update_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Delete_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Drop_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Reload_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Shutdown_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Process_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('File_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Grant_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('References_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Index_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Show_db_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Super_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_tmp_table_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Lock_tables_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Execute_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Repl_slave_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Repl_client_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_view_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Show_view_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_routine_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_routine_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_user_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Event_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Trigger_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_tablespace_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('ssl_type', mysql.ENUM('', 'ANY', 'X509', 'SPECIFIED'), server_default=sa.text("''"), nullable=False),
    sa.Column('ssl_cipher', sa.BLOB(), nullable=False),
    sa.Column('x509_issuer', sa.BLOB(), nullable=False),
    sa.Column('x509_subject', sa.BLOB(), nullable=False),
    sa.Column('max_questions', mysql.INTEGER(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('max_updates', mysql.INTEGER(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('max_connections', mysql.INTEGER(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('max_user_connections', mysql.INTEGER(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('plugin', mysql.CHAR(collation='utf8mb3_bin', length=64), server_default=sa.text("'caching_sha2_password'"), nullable=False),
    sa.Column('authentication_string', mysql.TEXT(collation='utf8mb3_bin'), nullable=True),
    sa.Column('password_expired', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('password_last_changed', mysql.TIMESTAMP(), nullable=True),
    sa.Column('password_lifetime', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('account_locked', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_role_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Drop_role_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Password_reuse_history', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('Password_reuse_time', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('Password_require_current', mysql.ENUM('N', 'Y'), nullable=True),
    sa.Column('User_attributes', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('Host', 'User'),
    comment='Users and global privileges',
    mysql_collate='utf8mb3_bin',
    mysql_comment='Users and global privileges',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('global_grants',
    sa.Column('USER', mysql.CHAR(collation='utf8mb3_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('HOST', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('PRIV', mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('WITH_GRANT_OPTION', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.PrimaryKeyConstraint('USER', 'HOST', 'PRIV'),
    comment='Extended global grants',
    mysql_collate='utf8mb3_bin',
    mysql_comment='Extended global grants',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('innodb_index_stats',
    sa.Column('database_name', mysql.VARCHAR(collation='utf8mb3_bin', length=64), nullable=False),
    sa.Column('table_name', mysql.VARCHAR(collation='utf8mb3_bin', length=199), nullable=False),
    sa.Column('index_name', mysql.VARCHAR(collation='utf8mb3_bin', length=64), nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('stat_name', mysql.VARCHAR(collation='utf8mb3_bin', length=64), nullable=False),
    sa.Column('stat_value', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('sample_size', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('stat_description', mysql.VARCHAR(collation='utf8mb3_bin', length=1024), nullable=False),
    sa.PrimaryKeyConstraint('database_name', 'table_name', 'index_name', 'stat_name'),
    mysql_collate='utf8mb3_bin',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('proxies_priv',
    sa.Column('Host', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8mb3_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('Proxied_host', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('Proxied_user', mysql.CHAR(collation='utf8mb3_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('With_grant', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('Grantor', mysql.VARCHAR(collation='utf8mb3_bin', length=288), server_default=sa.text("''"), nullable=False),
    sa.Column('Timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'User', 'Proxied_host', 'Proxied_user'),
    comment='User proxy privileges',
    mysql_collate='utf8mb3_bin',
    mysql_comment='User proxy privileges',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('password_history',
    sa.Column('Host', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8mb3_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('Password_timestamp', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('Password', mysql.TEXT(collation='utf8mb3_bin'), nullable=True),
    sa.PrimaryKeyConstraint('Host', 'User', 'Password_timestamp'),
    comment='Password history for user accounts',
    mysql_collate='utf8mb3_bin',
    mysql_comment='Password history for user accounts',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('columns_priv',
    sa.Column('Host', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('Db', mysql.CHAR(collation='utf8mb3_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8mb3_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('Table_name', mysql.CHAR(collation='utf8mb3_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Column_name', mysql.CHAR(collation='utf8mb3_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('Column_priv', mysql.SET('Select', 'Insert', 'Update', 'References', charset='utf8mb3', collation='utf8mb3_general_ci'), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'User', 'Db', 'Table_name', 'Column_name'),
    comment='Column privileges',
    mysql_collate='utf8mb3_bin',
    mysql_comment='Column privileges',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('replication_asynchronous_connection_failover_managed',
    sa.Column('Channel_name', mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=64), nullable=False, comment='The replication channel name that connects source and replica.'),
    sa.Column('Managed_name', mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=64), server_default=sa.text("''"), nullable=False, comment='The name of the source which needs to be managed.'),
    sa.Column('Managed_type', mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=64), server_default=sa.text("''"), nullable=False, comment='Determines the managed type.'),
    sa.Column('Configuration', mysql.JSON(), nullable=True, comment='The data to help manage group. For Managed_type = GroupReplication, Configuration value should contain {"Primary_weight": 80, "Secondary_weight": 60}, so that it assigns weight=80 to PRIMARY of the group, and weight=60 for rest of the members in mysql.replication_asynchronous_connection_failover table.'),
    sa.PrimaryKeyConstraint('Channel_name', 'Managed_name'),
    comment='The managed source configuration details',
    mysql_comment='The managed source configuration details',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('time_zone_name',
    sa.Column('Name', mysql.CHAR(length=64), nullable=False),
    sa.Column('Time_zone_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Name'),
    comment='Time zone names',
    mysql_comment='Time zone names',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('transaction',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('value', mysql.FLOAT(), nullable=False),
    sa.Column('transaction_date', mysql.DATETIME(), nullable=False),
    sa.Column('transfer_sender_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transfer_receiver_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['transfer_receiver_id'], ['account.id'], name='transaction_ibfk_2'),
    sa.ForeignKeyConstraint(['transfer_sender_id'], ['account.id'], name='transaction_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('help_category',
    sa.Column('help_category_id', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('name', mysql.CHAR(length=64), nullable=False),
    sa.Column('parent_category_id', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('url', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('help_category_id'),
    comment='help categories',
    mysql_comment='help categories',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('help_category', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)

    op.create_table('db',
    sa.Column('Host', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('Db', mysql.CHAR(collation='utf8mb3_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8mb3_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('Select_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Insert_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Update_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Delete_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Drop_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Grant_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('References_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Index_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_tmp_table_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Lock_tables_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_view_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Show_view_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_routine_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_routine_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Execute_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Event_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Trigger_priv', mysql.ENUM('N', 'Y'), server_default=sa.text("'N'"), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'User', 'Db'),
    comment='Database privileges',
    mysql_collate='utf8mb3_bin',
    mysql_comment='Database privileges',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('time_zone_transition',
    sa.Column('Time_zone_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Transition_time', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('Transition_type_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Time_zone_id', 'Transition_time'),
    comment='Time zone transitions',
    mysql_comment='Time zone transitions',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('account_type',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('drawing_limit', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('account_type', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)

    op.create_table('time_zone_leap_second',
    sa.Column('Transition_time', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('Correction', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Transition_time'),
    comment='Leap seconds information for time zones',
    mysql_comment='Leap seconds information for time zones',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('account',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=True),
    sa.Column('person_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('account_type_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text('(true)'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_type_id'], ['account_type.id'], name='account_ibfk_2'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name='account_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('help_keyword',
    sa.Column('help_keyword_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('name', mysql.CHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('help_keyword_id'),
    comment='help keywords',
    mysql_comment='help keywords',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('help_keyword', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)

    op.create_table('replication_asynchronous_connection_failover',
    sa.Column('Channel_name', mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=64), nullable=False, comment='The replication channel name that connects source and replica.'),
    sa.Column('Host', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), nullable=False, comment='The source hostname that the replica will attempt to switch over the replication connection to in case of a failure.'),
    sa.Column('Port', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False, comment='The source port that the replica will attempt to switch over the replication connection to in case of a failure.'),
    sa.Column('Network_namespace', mysql.CHAR(length=64), nullable=False, comment='The source network namespace that the replica will attempt to switch over the replication connection to in case of a failure. If its value is empty, connections use the default (global) namespace.'),
    sa.Column('Weight', mysql.TINYINT(unsigned=True), autoincrement=False, nullable=False, comment='The order in which the replica shall try to switch the connection over to when there are failures. Weight can be set to a number between 1 and 100, where 100 is the highest weight and 1 the lowest.'),
    sa.Column('Managed_name', mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=64), server_default=sa.text("''"), nullable=False, comment='The name of the group which this server belongs to.'),
    sa.PrimaryKeyConstraint('Channel_name', 'Host', 'Port', 'Network_namespace', 'Managed_name'),
    comment='The source configuration details',
    mysql_comment='The source configuration details',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('slow_log',
    sa.Column('start_time', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('user_host', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('query_time', mysql.TIME(fsp=6), nullable=False),
    sa.Column('lock_time', mysql.TIME(fsp=6), nullable=False),
    sa.Column('rows_sent', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rows_examined', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('db', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('last_insert_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('insert_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('server_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('sql_text', mysql.MEDIUMBLOB(), nullable=False),
    sa.Column('thread_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    comment='Slow log',
    mysql_comment='Slow log',
    mysql_default_charset='utf8mb3',
    mysql_engine='CSV'
    )
    op.create_table('time_zone_transition_type',
    sa.Column('Time_zone_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Transition_type_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Offset', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('Is_DST', mysql.TINYINT(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('Abbreviation', mysql.CHAR(length=8), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('Time_zone_id', 'Transition_type_id'),
    comment='Time zone transition types',
    mysql_comment='Time zone transition types',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('replication_group_configuration_version',
    sa.Column('name', mysql.CHAR(charset='ascii', collation='ascii_general_ci', length=255), nullable=False, comment='The configuration name.'),
    sa.Column('version', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False, comment='The version of the configuration name.'),
    sa.PrimaryKeyConstraint('name'),
    comment='The group configuration version.',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='The group configuration version.',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    # ### end Alembic commands ###
